services:
  jellyfin:
    image: jellyfin/jellyfin:10.10
    # image: lscr.io/linuxserver/jellyfin:10.10.7
    # image: lscr.io/linuxserver/jellyfin:latest
    user: 1000:1000
    group_add:
      - 1000
      - 992
      - video
    # network_mode: "host"
    networks:
      default:
        ipv4_address: 172.18.0.150
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    mem_limit: 4g
    restart: unless-stopped
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - JELLYFIN_PublishedServerUrl=http://192.168.43.150 #optional - alternative address used for autodiscovery
      - JELLYFIN_CACHE_DIR=/var/cache/jellyfin
      - JELLYFIN_CONFIG_DIR=/etc/jellyfin
      - JELLYFIN_DATA_DIR=/var/lib/jellyfin
      - JELLYFIN_LOG_DIR=/var/log/jellyfin
    volumes:
      - /home/lxc/jellyfin_data/etc:/etc/jellyfin
      - /home/lxc/jellyfin_data/cache:/var/cache/jellyfin
      - /home/lxc/jellyfin_data/lib:/var/lib/jellyfin
      - /home/lxc/jellyfin_data/log:/var/log/jellyfin
      - voldata1:/media/a407/NTHWD4
      - voldata2:/media/a407/NTHWD1
    devices:
      - /dev/dri:/dev/dri
      - /dev/dri/card1:/dev/dri/card1
      - /dev/dri/renderD128:/dev/dri/renderD128

volumes:
  voldata1:
    driver: local
    driver_opts:
      type: bind
      device: /media/nuc14/NTH_NAS_1
      o: bind
  voldata2:
    driver: local
    driver_opts:
      type: bind
      device: /media/nuc14/NTH_NAS_1/_tmp
      o: bind

networks:
  default:
    external: true
    name: dev
