version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin:10.10
    user: 1000:1000
    group_add:
      - 1000
      - 109
      - video
    network_mode: "host"
    restart: unless-stopped
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - JELLYFIN_CACHE_DIR=/var/cache/jellyfin
      - JELLYFIN_CONFIG_DIR=/etc/jellyfin
      - JELLYFIN_DATA_DIR=/var/lib/jellyfin
      - JELLYFIN_LOG_DIR=/var/log/jellyfin
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /etc/jellyfin:/etc/jellyfin
      - /var/cache/jellyfin:/var/cache/jellyfin
      - /var/lib/jellyfin:/var/lib/jellyfin
      - /var/log/jellyfin:/var/log/jellyfin
      - /media/a407/NTH_NAS_1:/media/a407/NTHWD4
      - voldata2:/media/a407/NTHWD1
    devices:
      # VAAPI Devices
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/renderD129:/dev/dri/renderD129
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/card1:/dev/dri/card1
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]

volumes:
  # voldata1:
  #   driver: local
  #   driver_opts:
  #     type: bind
  #     device: /media/a407/NTH_NAS_1
  #     o: bind
  voldata2:
    driver: local
    driver_opts:
      type: bind
      device: /media/a407/NTHWD1
      o: bind
